#!/bin/bash

set -e

source ./0.validate-parameter.sh
validateInputParameter "$1"

. /etc/os-release

install() {
  cd /opt
  sudo curl -Lo helix.tar.gz https://github.com/usagi-flow/evil-helix/releases/download/release-20250601/evil-helix-amd64-linux.tar.gz
  sudo tar -xf helix.tar.gz
  rm helix.tar.gz
  cd /usr/local/bin
  sudo ln -sv /opt/helix/hx .
  cd -
}

uninstall() {
  sudo rm /opt/helix
}

if [ "$1" == "--install" ]; then
  install
elif [ "$1" == "--uninstall" ]; then
  uninstall
else
  printf "%b\n" "${YELLOW}❌ Invalid parameter.${RC}"
  printf "%b\n" "${YELLOW}Usage: $0 --install / --uninstall${RC}"
  exit 1
fi
