#!/bin/bash

set -e

RC='\033[0m'
YELLOW='\033[33m'

source ./0.validate-parameter.sh
validateInputParameter "$1"

. /etc/os-release

install() {
  if [ "$ID" == "arch" ]; then
    sudo pacman -Sy --needed fastfetch
  elif [ "$ID" == "fedora" ]; then
    sudo dnf install -y fastfetch
  else
    printf "%b\n" "${YELLOW}No scripts present for ${ID}, exiting ...${RC}"
    exit 1
  fi
}

uninstall() {
  if [ "$ID" == "arch" ]; then
    sudo pacman -Rns fastfetch
  elif [ "$ID" == "fedora" ]; then
    sudo dnf remove -y fastfetch
    sudo dnf autoremove
  else
    printf "%b\n" "${YELLOW}No scripts present for ${ID}, exiting ...${RC}"
    exit 1
  fi
}

if [ "$1" == "--install" ]; then
  install
elif [ "$1" == "--uninstall" ]; then
  uninstall
else
  printf "%b\n" "${YELLOW}❌ Invalid parameter.${RC}"
  printf "%b\n" "${YELLOW}Usage: $0 --install / --uninstall${RC}"
  exit 1
fi
