#!/bin/bash

set -e

source ./0.validate-parameter.sh
validateInputParameter "$1"

. /etc/os-release

install() {
  if [ "$ID" == "arch" ]; then
    sudo pacman -Sy --needed spotify-launcher
  elif [ "$ID" == "fedora" ]; then
    flatpak install -y flathub com.spotify.Client
  else
    printf "%b\n" "${YELLOW}No scripts present for ${ID}, exiting ...${RC}"
    exit 1
  fi
}

uninstall() {
  if [ "$ID" == "arch" ]; then
    sudo pacman -Rns spotify-launcher
  elif [ "$ID" == "fedora" ]; then
    flatpak uninstall -y --delete-data flathub com.spotify.Client
    flatpak uninstall --unused
  else
    printf "%b\n" "${YELLOW}No scripts present for ${ID}, exiting ...${RC}"
    exit 1
  fi
}

if [ "$1" == "--install" ]; then
  install
elif [ "$1" == "--uninstall" ]; then
  uninstall
else
  printf "%b\n" "${YELLOW}❌ Invalid parameter.${RC}"
  printf "%b\n" "${YELLOW}Usage: $0 --install / --uninstall${RC}"
  exit 1
fi
