#!/bin/bash

RC='\033[0m'
YELLOW='\033[33m'
GREEN='\033[32m'
RED='\033[0;31m'

repolist=(
  "${HOME}/dotfiles"
  "${HOME}/Pictures"
  "${HOME}/Documents/obsidian"
  "${HOME}/Documents/books-and-pdfs"
  "${HOME}/Documents/projects/check-and-remove"
  "${HOME}/Documents/projects/DSA"
  "${HOME}/Documents/projects/exercism"
  "${HOME}/Documents/projects/intro-cs"
  "${HOME}/Projects/linops"
)

clear
for repo in "${repolist[@]}"; do
  printf "%-60s" "$repo"

  if [ ! -d "$repo" ]; then
    printf "%b\n" "${RED}Directory does not exist.${RC}"
  else
    cd "$repo" || continue

    if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
      printf "%b\n" "${YELLOW}Repository needs attention.${RC}"
    else
      printf "%b\n" "${GREEN}Repository is clean.${RC}"
    fi
  fi
done
