#!/bin/bash

RC='\033[0m'
YELLOW='\033[33m'
GREEN='\033[32m'
RED='\033[0;31m'

repolist=(
  # "/home/${USER}/dotfiles"
  "${HOME}/dotfiles"
  "${HOME}/Pictures"
  "${HOME}/Documents/obsidian"
  "${HOME}/Documents/books-and-pdfs"
  "${HOME}/Documents/linops"
  "${HOME}/Documents/projects/check-and-remove"
  "${HOME}/Documents/projects/DSA"
  "${HOME}/Documents/projects/exercism"
  "${HOME}/Documents/projects/intro-cs"
)

clear

printf "%b\n" "${YELLOW}************************ configured repos ************************${RC}"
for repo in "${repolist[@]}"; do
  printf "%b\n" "${GREEN}$repo${RC}"
done

printf "%b\n" "${YELLOW}******************** git status for each repo ********************${RC}"
for repo in "${repolist[@]}"; do
  printf "%b\n" "${GREEN}for '$repo':${RC}"
  if [ ! -d "$repo" ]; then
    printf "%b\n" "${RED}Directory '$repo' does not exist.${RC}"
  else
    cd "$repo" || continue
    if [ -n "$(git status --porcelain)" ]; then
      printf "%b\n" "${RED}Repository needs attention.${RC}"
    else
      printf "%b\n" "${GREEN}Repository is clean.${RC}"
    fi
  fi
  printf "%b\n" "${YELLOW}****************************************************************${RC}"
done
