#!/bin/bash

# Set to true when going directly to a submenu, so we can exit directly
BACK_TO_EXIT=false

back_to() {
  local parent_menu="$1"

  if [[ "$BACK_TO_EXIT" == "true" ]]; then
    exit 0
  elif [[ -n "$parent_menu" ]]; then
    "$parent_menu"
  else
    show_main_menu
  fi
}

menu() {
  local prompt="$1"
  local options="$2"
  local extra="$3"
  local preselect="$4"

  read -r -a args <<<"$extra"

  if [[ -n "$preselect" ]]; then
    local index
    index=$(echo -e "$options" | grep -nxF "$preselect" | cut -d: -f1)
    if [[ -n "$index" ]]; then
      args+=("-a" "$index")
    fi
  fi

  # echo -e "$options" | walker --dmenu --theme dmenu_250 -p "$prompt…" "${args[@]}"
  echo -e "$options" | rofi -dmenu -p "$prompt…" "${args[@]}"
}

show_system_menu() {
  # case $(menu "System" "  Lock\n󱄄  Screensaver\n󰤄  Suspend\n  Relaunch\n󰜉  Restart\n󰐥  Shutdown") in
  case $(menu "System" "  Lock\n󰍃  Logout\n󰜉  Restart\n󰐥  Shutdown") in
  *Lock*) swaylock ;;
  # *Logout*) hyprctl dispatch exit ;;
  # *Logout*) swaymsg exit ;;
  *Logout*) niri msg action quit ;;
  # *Suspend*) systemctl suspend ;;
  # *Relaunch*) uwsm stop ;;
  *Restart*) systemctl reboot ;;
  *Shutdown*) systemctl poweroff ;;
  *) back_to show_main_menu ;;
  esac
}

show_utilities_menu() {
  case $(menu "Utilities" "  xxxxxxxx") in
  *) show_main_menu ;;
  esac

}

show_main_menu() {
  # go_to_menu "$(menu "Go" "󰀻  Apps\n󰧑  Learn\n󱓞  Trigger\n  Style\n  Setup\n󰉉  Install\n󰭌  Remove\n  Update\n  About\n  System")"
  # go_to_menu "$(menu "Go" "󰃀  Quick links\n  Utilities\n  Keybindings\n󰍜  Toggle Waybar\n  Audio\n  Wifi\n󰂯  Bluetooth\n  System")"
  go_to_menu "$(menu "Choose" "󰃀  Quick links\n  Keybindings\n󰂯  Bluetooth\n  Audio\n  Wifi\n󰍜  Toggle Waybar\n  Utilities\n  System")"
}

go_to_menu() {
  case "${1,,}" in
  *quick*) ~/Documents/linops/scripts/quicklinks.sh ;;
  # *apps*) walker -p "Launch…" ;;
  *keybindings*) ~/Documents/linops/scripts/keybindings.sh ;;
  # *learn*) show_learn_menu ;;
  # *toggle*) show_toggle_menu ;;
  # *audio*) $TERMINAL --class=Wiremix -e wiremix ;;
  *bluetooth*) pidof bluetui || kitty --class=Bluetui -e bluetui ;;
  *audio*) pidof wiremix || kitty --class=Wiremix -e wiremix ;;
  *wifi*) pidof nmtui || kitty --class=NMtui-go -e nmtui ;;
  *toggle*) ~/Documents/linops/scripts/toggle-waybar ;;
  *utilities*) show_utilities_menu ;;
  *system*) show_system_menu ;;
  esac
}

if [[ -n "$1" ]]; then
  BACK_TO_EXIT=true
  go_to_menu "$1"
else
  show_main_menu
fi
