#! /usr/bin/env bash

TERMINAL="foot"

function tmux_sessions() {
  tmux list-session -F '#S'
}

TMUX_SESSION=$( (
  echo "Create new session…"
  tmux_sessions
) | rofi -dmenu -i -p "Tmux sessions" -matching fuzzy)

if [[ x"Create new session…" = x"${TMUX_SESSION}" ]]; then
  name=$(
    rofi -dmenu -i -p "session name: " -l 0 -matching fuzzy \
      -theme ~/.config/rofi/input.rasi
  )
  [ -n "$name" ] || exit 0
  swaymsg '[workspace="3" app_id="foot"]' kill || true
  # pkill -x $TERMINAL 2>/dev/null || true
  sleep 0.1
  # create and attach
  exec $TERMINAL -e tmux new-session -s "$name" &
  exit 0
elif [[ -z "${TMUX_SESSION}" ]]; then
  exit 0
else
  swaymsg '[workspace="3" app_id="foot"]' kill || true
  # pkill -x $TERMINAL 2>/dev/null || true
  sleep 0.1
  exec $TERMINAL -e tmux attach -t "${TMUX_SESSION}" &
fi
