#!/bin/bash

set -e

RC='\033[0m'
YELLOW='\033[33m'

. /etc/os-release

if [ "$ID" == "arch" ]; then
  yay -Rc brave-bin
elif [ "$ID" == "fedora" ]; then
  printf "%b\n" "${YELLOW}TODO ...${RC}"
else
  printf "%b\n" "${YELLOW}No scripts present for ${ID}, exiting ...${RC}"
  exit 1
fi
